workflows:
  ios-main:
    name: ios Main

    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "{{ ADD WORKSPACE NAME HERE }}"
        XCODE_SCHEME: "{{ ADD SCHEME NAME HERE }}"
      flutter: stable
      xcode: latest

    scripts:
      - xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

